CREATE TABLE `user` (
    `id` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    `name` VARCHAR(255) ,
    `avatar` VARCHAR(255) ,
    `phone_number` VARCHAR(12) NOT NULL UNIQUE,
    `password` VARCHAR(191) ,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);